networks:
     network:
       default:
         name: kuksa-network
services:
  kuksa-val-server:
    container_name: kuksa-val-server
    build: ./images/kuksa-val-server
    ports:
      - 8080:8080
  kuksa-databroker:
    container_name: kuksa-databroker
    build: ./images/kuksa-databroker
    ports:
      - 55555:55555
  kuksa-client:
    container_name: kuksa-client
    build: ./images/kuksa-client
    command: ["sleep", "infinity"]
    environment:
      - KUKSA_DATABROKER_HOST=kuksa-databroker
      - KUKSA_SERVER_HOST=kuksa-val-server
    links:
      - kuksa-val-server
      - kuksa-databroker
    depends_on:
      - kuksa-val-server
      - kuksa-databroker
