# /********************************************************************************
# * Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

# This is expected to be executed in the kuksa.val top-level directory

# This builds KUKSA databroker
FROM registry.fedoraproject.org/fedora:38

RUN dnf  -y update && dnf install -y \
protobuf-compiler \
protobuf \
protobuf-devel \
patch \
cmake \
g++ \
wget \
libstdc++ \
bzip2 \
grpc \
grpc-cpp \
grpc-devel \
boost \
boost-devel \
mosquitto \
mosquitto-devel \
rust \
rust-src \
git \
cargo \
@development-tools \
openssl-devel  && rm -rf /var/lib/apt/lists/* 

RUN git clone https://github.com/eclipse/kuksa.val.git

ENV SRC="/home/rust/src"
WORKDIR ${SRC}
RUN ls -al
RUN cargo new project
RUN cp -rf ${SRC}/project/ ../.
RUN ls -al
WORKDIR ${SRC}/project
RUN ls -al
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

RUN cargo install cargo-license
ENV PATH=/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# We need to add all files, because .git directory is needed to
# extract verson information during build, and we can not leave
# files out, if we do not want -dirty tags on every build
# Does not influence final image size due to multistage build
COPY . .

WORKDIR ${SRC}/project
ENV RUST_BACKTRACE=full
RUN cat Cargo.toml
RUN cargo install cargo-dependency-inheritor
RUN cargo dependency-inheritor --workspace-path ${SRC}/project/Cargo.toml -n 1
RUN cargo build --release

ENV KUKSA_DATA_BROKER_ADDR=0.0.0.0
ENV KUKSA_DATA_BROKER_PORT=55555

EXPOSE $KUKSA_DATA_BROKER_PORT

ENTRYPOINT [ "/bin/bash" ]
