# /********************************************************************************
# * Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

# This is expected to be executed in the kuksa.val top-level directory

# This builds KUKSA databroker
FROM registry.fedoraproject.org/fedora:38 AS builder

RUN dnf  -y update && dnf install -y \
automake \
protobuf-compiler \
protobuf \
protobuf-devel \
patch \
cmake \
g++ \
gcc \
gcc-c++ \
kernel-devel \
wget \
libstdc++ \
bzip2 \
grpc \
grpc-cpp \
grpc-devel \
boost \
boost-devel \
mosquitto \
mosquitto-devel \
rust \
rust-src \
git \
cargo \
@development-tools \
openssl-devel \
python3-yaml \
net-tools \
iputils \
iproute \
python3-devel \
pip

ENV SRC="/home/rust/src"

WORKDIR ${SRC}

RUN git clone https://github.com/eclipse/kuksa.val.git
RUN git clone https://github.com/COVESA/vehicle_signal_specification.git

WORKDIR ${SRC}/kuksa.val/target

RUN cp -rf ${SRC}/kuksa.val/kuksa_databroker/databroker .
RUN cp -rf ${SRC}/vehicle_signal_specification/ .

WORKDIR ${SRC}/kuksa.val/target/vehicle_signal_specification/

RUN rm -rf vss-tools
RUN git clone https://github.com/COVESA/vss-tools.git
RUN pip install anytree setuptools gql[all] graphql-core
RUN ${SRC}/kuksa.val/target/vehicle_signal_specification/vss-tools/vspec2json.py -I ./spec ./spec/VehicleSignalSpecification.vspec vss.json
RUN chmod +x vss.json

WORKDIR ${SRC}/kuksa.val/kuksa_databroker/databroker

ENV PATH=/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN cargo install cargo-license

# We need to add all files, because .git directory is needed to
# extract verson information during build, and we can not leave
# files out, if we do not want -dirty tags on every build
# Does not influence final image size due to multistage build
COPY . .

WORKDIR ${SRC}/kuksa.val/kuksa_databroker

RUN (cd createbom; python3 createbom.py ../databroker)
RUN cargo build --release

WORKDIR ${SRC}/kuksa.val/target/release

FROM registry.fedoraproject.org/fedora:38

ENV SRC="home/rust/src"
RUN mkdir -p /usr/bin/release
COPY --from=builder ${SRC}/kuksa.val/target/release/databroker /usr/bin/data-broker
COPY --from=builder ${SRC}/kuksa.val/target/release/databroker-cli /usr/bin/data-broker-cli
COPY --from=builder ${SRC}/kuksa.val/target/ /usr/bin/release
COPY --from=builder ${SRC}/kuksa.val/target/vehicle_signal_specification/vss.json /usr/bin/release

RUN ls -al /usr/bin/release/
ENV KUKSA_DATA_BROKER_ADDR=0.0.0.0
ENV KUKSA_DATA_BROKER_PORT=55555
ENV KUKSA_DATA_BROKER_METADATA_FILE=vss.json

EXPOSE $KUKSA_DATA_BROKER_PORT

ENTRYPOINT ["/usr/bin/data-broker"]
CMD ["--vss", "/usr/bin/release/vss.json"]
