FROM registry.fedoraproject.org/fedora:38

RUN dnf  -y update && dnf install -y \
protobuf-compiler \
protobuf \
protobuf-devel \
grpc \
grpc-cpp \
grpc-devel \
python3-devel \
pip

RUN pip install -U kuksa-client

COPY files/ /

ENTRYPOINT ["/bin/bash", "-c"]

CMD ["sleep", "infinity"]
