FROM registry.fedoraproject.org/fedora:38 AS builder

ENV HOME=/root
ENV DIR=/tmp/ibeji/target/release
ENV PATH=$HOME/.cargo/bin:$PATH

RUN dnf  -y update && dnf install -y \
automake \
fontconfig-devel \
pkg-config \
protobuf-compiler \
protobuf \
protobuf-devel \
patch \
cmake \
g++ \
gcc \
gcc-c++ \
kernel-devel \
wget \
libstdc++ \
bzip2 \
grpc \
grpc-cpp \
grpc-devel \
boost \
boost-devel \
mosquitto \
mosquitto-devel \
rust \
rust-src \
git \
cargo \
@development-tools \
openssl-devel \
python3-yaml \
net-tools \
iputils \
iproute \
python3-devel \
pip

RUN cargo install cargo-license

WORKDIR /tmp

RUN git clone --recurse-submodules https://github.com/eclipse-ibeji/ibeji
RUN dnf remove rustc -y
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN source $HOME/.cargo/env

WORKDIR /tmp/ibeji
RUN cargo build --release

RUN cp core/invehicle-digital-twin/template/invehicle_digital_twin_settings.yaml $DIR/invehicle_digital_twin_settings.yaml
RUN echo 'invehicle_digital_twin_authority: "0.0.0.0:5010"' > $DIR/invehicle_digital_twin_settings.yaml

RUN cp samples/common/template/consumer_settings.yaml $DIR/consumer_settings.yaml
RUN echo 'invehicle_digital_twin_uri: "http://0.0.0.0:5010"' > $DIR/consumer_settings.yaml

RUN cp samples/common/template/provider_settings.yaml $DIR/provider_settings.yaml
RUN echo 'invehicle_digital_twin_uri: "http://0.0.0.0:5010"' > $DIR/provider_settings.yaml
