FROM registry.fedoraproject.org/fedora:38 as build

RUN yum -y update && yum install -y cmake g++ wget openssl-devel libstdc++ bzip2 git

#Build Boost 1.75
ENV BOOST_VER=1.75.0
ENV BOOST_VER_=1_75_0
RUN wget   https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VER}/source/boost_${BOOST_VER_}.tar.bz2
RUN tar xvjf boost_${BOOST_VER_}.tar.bz2
WORKDIR /boost_${BOOST_VER_}
RUN ./bootstrap.sh
#RUN ./b2 -j 6 install

WORKDIR /
# Build and install grpc
ENV GRPC_VER=1.44.0
RUN git clone --recurse-submodules -b v${GRPC_VER}  --single-branch --depth 1 --shallow-submodules https://github.com/grpc/grpc
RUN mkdir -p /grpc/build
WORKDIR /grpc/build
RUN cmake -DgRPC_INSTALL=ON  -DgRPC_BUILD_TESTS=OFF -DgRPC_SSL_PROVIDER=package ..
#RUN make -k -j 6
#RUN make install
RUN mkdir -p /grpc/third_party/abseil-cpp/build
WORKDIR /grpc/third_party/abseil-cpp/build
RUN cmake -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE ..
#RUN make -k -j 6
#RUN make install

ADD . /kuksa.val
RUN rm -rf /kuksa.val/kuksa-val-server/build &&  mkdir -p /kuksa.val/kuksa-val-server/build
WORKDIR /kuksa.val
RUN ls -al
WORKDIR /kuksa.val/kuksa-val-server
RUN ls -al
#WORKDIR /kuksa.val
RUN cmake ..
RUN make -j 4
RUN ls
RUN /kuksa.val/kuksa-val-server/docker/collect-deployment-artifacts.sh

FROM registry.fedoraproject.org/fedora:38 as build

COPY --from=build /deploy /kuksa.val
WORKDIR /kuksa.val

ENV LOG_LEVEL=INFO
#Usually you want this to be 0.0.0.0 when using porter port expose via -p.
ENV BIND_ADDRESS=0.0.0.0

EXPOSE 8090/tcp

CMD /kuksa.val/startkuksaval.sh
