FROM registry.fedoraproject.org/fedora:38 as build

RUN dnf -y update && dnf install -y cmake g++ wget openssl-devel libstdc++ bzip2 git protobuf protobuf-devel grpc

#Build Boost 1.75
ENV BOOST_VER=1.75.0
ENV BOOST_VER_=1_75_0

ADD . /
RUN git clone --recursive https://github.com/eclipse/kuksa.val.git
RUN cd /kuksa.val/kuksa-val-server
RUN ls -al
RUN mkdir build
RUN cd build
RUN cmake -DMOSQUITTO_INCLUDE_DIR=/kuksa.val/kuksa-val-server/src ..
RUN make -j 4
RUN make install
RUN ls
RUN /kuksa.val/kuksa-val-server/docker/collect-deployment-artifacts.sh

#FROM registry.fedoraproject.org/fedora:38 as build

COPY --from=build /deploy /kuksa.val
WORKDIR /kuksa.val

ENV LOG_LEVEL=INFO
#Usually you want this to be 0.0.0.0 when using porter port expose via -p.
ENV BIND_ADDRESS=0.0.0.0

EXPOSE 8090/tcp

CMD /kuksa.val/startkuksaval.sh
